### PR TITLE
Updated version to work with newest wireless bridge

### PR DESCRIPTION
**Pull request by dudeofawesome**

### CODE REVIEW

**Comment by Narvey** [comment]
Well, I think there is still a way we can make them compatible, at the very least by adding a setting.
I don't have the time to do that tonight, but when I get the chance I will, and then I'll merge your branch.

Hey, what do you think about making a GUI, kinda like these folks do? https://32dad57ebfdb2ad9012d1c909b41ba5e19c64c5a.googledrive.com/host/0ByfFwjYTfWSbS2d3dWtERE9TVUE/

**Comment by dudeofawesome** [comment]
Adding a GUI shouldn't be too difficult.  What I would really like from this project though is for it to work on OSX and Linux, too. I'll take a look at the GUI part if you can add that switch for older bridge models.

It would be good to simply save the last used bridge in the settings, and assume that bridge is the one the user wants unless the specify otherwise.

**Comment by Narvey** [comment]
I already have it working on a Linux box, btw.  You might check to see if it is possible to install mono on OSX.

**Comment by triforcegathering** [comment]
What do you all think about including a compiled build on this repo? Right now, this is the only CLI for these bulbs that works on Windows. I'm sure some people who don't know how to compile would appreciate it. I barely was able to compile it myself.

**Comment by dudeofawesome** [comment]
Absolutely. Unfortunately, I don't have an install of VS on Windows anymore. Maybe @Narvey can make one and add it to releases.

I do have Xamarin Studio on OSX though, and can build it for Mac from there. I'm about to add the Mac build to releases.

**Comment by triforcegathering** [comment]
Hey, mind reviewing my pull request? I'd like to add some functions to this.

**Comment by Narvey** [comment]
Can you get this attachment?  If so, rename the .abc to .exe and you will
get a version for the old bridge.

Nathan Harvey

**Comment by Narvey** [comment]
I'm sorry, I'm super busy at work and haven't had time to merge the current pull request.  And to make it more difficult, my installation of git is corrupted.

**Comment by Narvey** [comment]
Let's see if that worked.  If anything went wrong, feel free to make another pull request (I'll try to take care of it much faster this time).

**Pull request merged**
